// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: halbornctf/hal/redeem_request.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type RedeemRequest struct {
	Account        string     `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Collateral     types.Coin `protobuf:"bytes,2,opt,name=collateral,proto3" json:"collateral"`
	Completiontime time.Time  `protobuf:"bytes,3,opt,name=completiontime,proto3,stdtime" json:"completiontime" yaml:"completion_time"`
}

func (m *RedeemRequest) Reset()         { *m = RedeemRequest{} }
func (m *RedeemRequest) String() string { return proto.CompactTextString(m) }
func (*RedeemRequest) ProtoMessage()    {}
func (*RedeemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_218f3ac7c3084d76, []int{0}
}
func (m *RedeemRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RedeemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RedeemRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RedeemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedeemRequest.Merge(m, src)
}
func (m *RedeemRequest) XXX_Size() int {
	return m.Size()
}
func (m *RedeemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RedeemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RedeemRequest proto.InternalMessageInfo

func (m *RedeemRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *RedeemRequest) GetCollateral() types.Coin {
	if m != nil {
		return m.Collateral
	}
	return types.Coin{}
}

func (m *RedeemRequest) GetCompletiontime() time.Time {
	if m != nil {
		return m.Completiontime
	}
	return time.Time{}
}

func init() {
	proto.RegisterType((*RedeemRequest)(nil), "halbornctf.hal.RedeemRequest")
}

func init() {
	proto.RegisterFile("halbornctf/hal/redeem_request.proto", fileDescriptor_218f3ac7c3084d76)
}

var fileDescriptor_218f3ac7c3084d76 = []byte{
	// 313 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xc1, 0x4a, 0xf3, 0x40,
	0x14, 0x85, 0x33, 0xff, 0x2f, 0x8a, 0x11, 0xbb, 0x08, 0x52, 0x62, 0x17, 0x93, 0x12, 0x37, 0x5d,
	0xcd, 0x58, 0xdd, 0xb9, 0x11, 0x5a, 0x10, 0xd7, 0xa1, 0x2b, 0x37, 0x65, 0x32, 0xde, 0xa6, 0x81,
	0x49, 0x6e, 0xcc, 0x4c, 0xc5, 0xbe, 0x45, 0x1f, 0xab, 0xcb, 0xe2, 0xca, 0x55, 0x95, 0xf6, 0x0d,
	0x7c, 0x02, 0xc9, 0x4c, 0x4b, 0xc5, 0xdd, 0xbd, 0xdc, 0x73, 0xcf, 0xf9, 0x38, 0xfe, 0xd5, 0x54,
	0xa8, 0x14, 0xeb, 0x52, 0x9a, 0x09, 0x9f, 0x0a, 0xc5, 0x6b, 0x78, 0x06, 0x28, 0xc6, 0x35, 0xbc,
	0xcc, 0x40, 0x1b, 0x56, 0xd5, 0x68, 0x30, 0x68, 0x1d, 0x44, 0x6c, 0x2a, 0x54, 0xe7, 0x22, 0xc3,
	0x0c, 0xed, 0x89, 0x37, 0x93, 0x53, 0x75, 0xa8, 0x44, 0x5d, 0xa0, 0xe6, 0xa9, 0xd0, 0xc0, 0x5f,
	0xfb, 0x29, 0x18, 0xd1, 0xe7, 0x12, 0xf3, 0x72, 0x77, 0x8f, 0x32, 0xc4, 0x4c, 0x01, 0xb7, 0x5b,
	0x3a, 0x9b, 0x70, 0x93, 0x17, 0xa0, 0x8d, 0x28, 0x2a, 0x27, 0x88, 0xdf, 0x89, 0x7f, 0x9e, 0xd8,
	0xfc, 0xc4, 0xc5, 0x07, 0xa1, 0x7f, 0x22, 0xa4, 0xc4, 0x59, 0x69, 0x42, 0xd2, 0x25, 0xbd, 0xd3,
	0x64, 0xbf, 0x06, 0xf7, 0xbe, 0x2f, 0x51, 0x29, 0x61, 0xa0, 0x16, 0x2a, 0xfc, 0xd7, 0x25, 0xbd,
	0xb3, 0x9b, 0x4b, 0xe6, 0x08, 0x58, 0x43, 0xc0, 0x76, 0x04, 0x6c, 0x88, 0x79, 0x39, 0x38, 0x5a,
	0xae, 0x23, 0x2f, 0xf9, 0xf5, 0x12, 0x4c, 0xfc, 0x96, 0xc4, 0xa2, 0x52, 0x60, 0x72, 0x2c, 0x1b,
	0x92, 0xf0, 0xbf, 0x35, 0xe9, 0x30, 0x87, 0xc9, 0xf6, 0x98, 0x6c, 0xb4, 0xc7, 0x1c, 0xc4, 0x8d,
	0xcb, 0xf7, 0x3a, 0x6a, 0xcf, 0x45, 0xa1, 0xee, 0xe2, 0xc3, 0xff, 0xb8, 0x31, 0x88, 0x17, 0x9f,
	0x11, 0x49, 0xfe, 0xb8, 0x0e, 0xae, 0x97, 0x1b, 0x4a, 0x56, 0x1b, 0x4a, 0xbe, 0x36, 0x94, 0x2c,
	0xb6, 0xd4, 0x5b, 0x6d, 0xa9, 0xf7, 0xb1, 0xa5, 0xde, 0x53, 0xfb, 0xd1, 0xb5, 0x3a, 0x1c, 0x3d,
	0xf0, 0x37, 0x5b, 0xbe, 0x99, 0x57, 0xa0, 0xd3, 0x63, 0x9b, 0x7c, 0xfb, 0x13, 0x00, 0x00, 0xff,
	0xff, 0x8b, 0x73, 0x6a, 0x18, 0x9b, 0x01, 0x00, 0x00,
}

func (m *RedeemRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RedeemRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RedeemRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.Completiontime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.Completiontime):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintRedeemRequest(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.Collateral.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintRedeemRequest(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Account) > 0 {
		i -= len(m.Account)
		copy(dAtA[i:], m.Account)
		i = encodeVarintRedeemRequest(dAtA, i, uint64(len(m.Account)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintRedeemRequest(dAtA []byte, offset int, v uint64) int {
	offset -= sovRedeemRequest(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *RedeemRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Account)
	if l > 0 {
		n += 1 + l + sovRedeemRequest(uint64(l))
	}
	l = m.Collateral.Size()
	n += 1 + l + sovRedeemRequest(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.Completiontime)
	n += 1 + l + sovRedeemRequest(uint64(l))
	return n
}

func sovRedeemRequest(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozRedeemRequest(x uint64) (n int) {
	return sovRedeemRequest(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *RedeemRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRedeemRequest
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RedeemRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RedeemRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Account", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRedeemRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRedeemRequest
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRedeemRequest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Account = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Collateral", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRedeemRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRedeemRequest
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRedeemRequest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Collateral.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Completiontime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRedeemRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRedeemRequest
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRedeemRequest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.Completiontime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRedeemRequest(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRedeemRequest
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipRedeemRequest(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowRedeemRequest
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRedeemRequest
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRedeemRequest
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthRedeemRequest
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupRedeemRequest
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthRedeemRequest
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthRedeemRequest        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowRedeemRequest          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupRedeemRequest = fmt.Errorf("proto: unexpected end of group")
)
